### ISSUE TITLE
Could I get your code ？

### ISSUE THREAD

**Issue by baoy-nlp** [pcyin/structVAE#1]
Hi, pcyin, 
I am very interested in the paper "StructVAE: Tree-structured Latent Variable Models for Semi-supervised Semantic Parsing. The 56th Annual Meeting of the Association for Computational Linguistics (ACL). July 2018." 
Could i get the code in this repository?

**Comment by pcyin** [comment]
Hey, I am so sorry for the delay! I will release the code asap.
